Oz information panel
pacien/ldgallery pull request #238
Opened 2020-09-10 22:17 UTC by zeroinformatique

2020-09-10 23:39 UTC, pacien requested changes
I added a few remarks that need to be addressed. Please fix those issues and re-assign this PR to me so I can add the relevant documentation before merging.

2020-09-10 23:39 UTC, pacien commented on example/config.json
> +	"initialTagDisplayLimit": 10,
Indent mismatch.

2020-09-10 23:39 UTC, pacien commented on viewer/src/assets/scss/scrollbar.scss
> +@import "~@/assets/scss/theme.scss";
Missing copyright and license header.

2020-09-10 23:39 UTC, pacien commented on viewer/src/assets/scss/transition.scss
> +@import "~@/assets/scss/theme.scss";
Missing copyright and license header.

2020-09-10 23:39 UTC, pacien commented on viewer/src/components/LdCommandSort.vue
> +.ml1 {
Please use a more explicit name, like `.dropdownLabel`.

2020-09-10 23:39 UTC, pacien commented on viewer/src/components/LdProposition.vue
> +  readonly INITIAL_TAG_DISPLAY_LIMIT = this.$galleryStore.config?.initialTagDisplayLimit ?? 10;
Question: what's happening if this number is negative?

2020-09-10 23:39 UTC, pacien commented on viewer/src/locales/en.json
> +  "command.sort.byDateDesc": "By most recent"
"By most recent" doesn't make sense; this should be "By date (most recent first)".

2020-09-10 23:39 UTC, pacien commented on viewer/src/services/itemSortFn.ts
> +  static sortByName(left: Gallery.Item, right: Gallery.Item): number {
Should be named more explicitly `sortByNameDesc`, like the other function below.

2020-09-10 23:39 UTC, pacien commented on viewer/src/views/PanelLeft.vue
> +.flexShrink1000 {
Could be named more explicitly. Something like `.shrinkFully` which denotes that this will shrink fully in the presence of another element taking the full height. Adding a class with the exact same name as the property and value being set doesn't bring any benefit compared to dirty inlining.

2020-09-10 23:39 UTC, pacien commented on viewer/src/locales/en.json
> +  "command.sort.byName": "By name",
This could be more precise: "By name (A to Z)".

2020-09-10 23:39 UTC, pacien commented on viewer/src/components/LdProposition.vue
> +  get showMore(): number {
This method doesn't do the action of "showing". It should perhaps be named `hiddenPropositionsCount` instead.

2020-09-11 13:12 UTC, pacien commented on viewer/src/components/LdProposition.vue
> +  readonly INITIAL_TAG_DISPLAY_LIMIT = this.$galleryStore.config?.initialTagDisplayLimit ?? 10;
Actually, setting this to zero should disable the tag limit feature.

2020-09-11 18:00 UTC, zeroinformatique commented on viewer/src/components/LdProposition.vue
> +  readonly INITIAL_TAG_DISPLAY_LIMIT = this.$galleryStore.config?.initialTagDisplayLimit ?? 10;
A negative number would remove X elements at the end of the list (so -10) will remove the 10 last elements.
I added a filter so if <=0 it will use 1000 as an hard limit. It's very high and should never occur in production since it doesn't make sense to display so many tags.

2020-09-11 18:04 UTC, zeroinformatique commented on viewer/src/components/LdProposition.vue
> +  get showMore(): number {
I prefer to keep it linked to what's on the screen; it's easier to understand what it is used for. But I'll rename it to showMoreCount()

2020-09-11 18:57 UTC, pacien commented on viewer/src/assets/scss/scrollbar.scss
> +-- Copyright (C) 2020       Pacien TRAN-GIRARD
That should be your name here @zeroinformatique ;)

2020-09-11 18:57 UTC, pacien commented on viewer/src/assets/scss/transition.scss
> +-- Copyright (C) 2020       Pacien TRAN-GIRARD
That should be your name here @zeroinformatique ;)

2020-09-11 18:57 UTC, pacien commented on viewer/src/components/LdProposition.vue
> +    return limit > 0 ? limit : 1000;
Actually let's disable the tag hiding feature for `-1`, because 0 actually makes sense to collapse all categories by default.
Sorry for the change of plan!

2020-09-11 19:14 UTC, pacien commented on example/config.json
> +	"galleryIndex": "index.json",
Indent mismatch again :/

2020-09-11 19:52 UTC, pacien approved these changes

2020-09-11 19:53 UTC, merged